name: ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build & Test
    strategy:
      matrix:
        features: ["--all-features", "--no-default-features"]
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo build -r ${{ matrix.features }} --workspace
      - run: cargo test -r ${{ matrix.features }} --workspace

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: cargo clippy --workspace --all-targets

  docs:
    name: Docs
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo doc --workspace --no-deps

  msrv:
    runs-on: ubuntu-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-no-dev-deps
      - uses: dtolnay/rust-toolchain@1.67.1
      - run: cargo no-dev-deps check
